name: Generar APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Buildozer
        uses: ArtemSerebrennikov/buildozer-action@v1
        with:
          command: buildozer android debug
          repository_root: .
      - name: Descargar APK
        uses: actions/upload-artifact@v3
        with:
          name: Mi_App_Personalizada
          path: bin/*.apk
