name: Generar APK Real
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Instalar Herramientas de Python
        run: |
          sudo apt update
          sudo apt install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip3 install --user --upgrade Cython==0.29.33 buildozer

      - name: Crear la APK
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # Esto ignora errores de red y fuerza la compilaci√≥n
          yes | buildozer android debug

      - name: Subir APK Final
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: APK_Lista_Para_Instalar
          path: bin/*.apk
